export const languages = [
    { label: "English" },
    { label: "Español - España (Spanish - Spain)" },
    { label: "Français (French)" },
    { label: "Italiano (Italian)" },
    { label: "Deutsch (German)" },
    { label: "Ελληνικά (Greek)" },
    { label: "한국어 (Korean)" },
    { label: "简体中文 (Simplified Chinese)" },
    { label: "繁體中文 (Traditional Chinese)" },
    { label: "Русский (Russian)" },
    { label: "ไทย (Thai)" },
    { label: "日本語 (Japanese)" },
    { label: "Português - Portugal (Portuguese - Portugal)" },
    { label: "Português - Brasil (Portuguese - Brazil)" },
    { label: "Polski (Polish)" },
    { label: "Dansk (Danish)" },
    { label: "Nederlands (Dutch)" },
    { label: "Suomi (Finnish)" },
    { label: "Norsk (Norwegian)" },
    { label: "Svenska (Swedish)" },
    { label: "Čeština (Czech)" },
    { label: "Magyar (Hungarian)" },
    { label: "Română (Romanian)" },
    { label: "Български (Bulgarian)" },
    { label: "Türkçe (Turkish)" },
    { label: "Українська (Ukrainian)" },
    { label: "Tiếng Việt (Vietnamese)" },
    { label: "Español - Latinoamérica (Spanish - Latin America)" }
];